### ISSUE TITLE
Couple of issues with Koajs OpenCollective (money not arriving at intended destination)

### ISSUE THREAD

**Issue by ThePurpleRabbits** [opencollective/opencollective-api#474]
Couple of issues:

[https://github.com/koajs/koa/issues/770](https://github.com/koajs/koa/issues/770)

and

[https://github.com/koajs/koa/issues/767](https://github.com/koajs/koa/issues/767)

Could you sort it out so the money gets to the right people as soon as possible.

Thanks.

**Comment by ThePurpleRabbits** [comment]
Also the having our name and Clown-Fox's blog on the backers list but our priority is that the coders get the money I paid to them.

**Comment by piamancini** [comment]
Hi @ThePurpleRabbits 

The way OpenCollective works is that TJ and the rest of the Koa team need to submit and expense/invoice in order to retrieve the money. It's their money and it's sitting in their collective until they decide to use it. We don't make automatic transfers. The reason they use OpenCollective is that they don't want to receive the money directly into their accounts and then manage it themselves. So the funds are stored in their public page https://opencollective.com/koajs and when they submit an expense or an invoice to be paid, the funds are sent via paypal. 

I'll look now into why you guys are not showing up on their readme.

**Comment by ThePurpleRabbits** [comment]
That's a good idea. When they need it they'll know why they need it. Important. I am hopeful about this issue now.

**Comment by piamancini** [comment]
exactly!

**Comment by clarete** [comment]
I'll close this issue for lack of activity but please feel free to reopen if there's anything else that we missed!
